use std::path::Path;

use anyhow::{Result, bail};

pub const ALL: &[&str] = &[
    "production",
    "test",
    "fixture",
    "generated",
    "documentation",
    "unknown",
];

pub const DEFAULT_EXPANSION: &[&str] = &["production", "unknown"];

pub fn classify(path: &Path, source: &str) -> &'static str {
    let normalized = path.to_string_lossy().replace('\\', "/").to_lowercase();
    let components: Vec<&str> = normalized
        .split('/')
        .filter(|part| !part.is_empty())
        .collect();
    let file = components.last().copied().unwrap_or_default();
    let mut header_end = source.len().min(4096);
    while header_end > 0 && !source.is_char_boundary(header_end) {
        header_end -= 1;
    }
    let header = source[..header_end].to_lowercase();

    if generated_path(&components, file) || generated_header(&header) {
        "generated"
    } else if has_component(
        &components,
        &[
            "fixture",
            "fixtures",
            "__fixtures__",
            "mock",
            "mocks",
            "__mocks__",
            "stub",
            "stubs",
        ],
    ) || has_file_marker(file, &[".fixture.", ".fixtures.", ".mock.", ".stub."])
    {
        "fixture"
    } else if has_component(
        &components,
        &[
            "test",
            "tests",
            "__tests__",
            "testing",
            "spec",
            "specs",
            "e2e",
            "test-utils",
            "test_utils",
            "integration-tests",
        ],
    ) || has_file_marker(
        file,
        &[
            ".test.",
            ".spec.",
            ".e2e.",
            ".e2e-spec.",
            ".integration-test.",
        ],
    ) || matches!(file, "test.rs" | "tests.rs")
    {
        "test"
    // Singular `doc` is deliberately not a documentation marker: document-
    // domain production code commonly uses that directory name. `docs` and
    // `documentation` remain coarse bootstrap signals until evidence-backed
    // repository reconnaissance can supply a semantic scope-role overlay.
    } else if has_component(
        &components,
        &["docs", "documentation", ".storybook", "stories"],
    ) || has_file_marker(file, &[".stories.", ".story."])
    {
        "documentation"
    } else {
        "production"
    }
}

pub fn validate_all(roles: &[String]) -> Result<()> {
    for role in roles {
        if !ALL.contains(&role.as_str()) {
            bail!("file role must be one of: {}; got `{role}`", ALL.join(", "));
        }
    }
    Ok(())
}

pub fn penalty(role: Option<&str>) -> f64 {
    match role {
        Some("production") | None => 1.0,
        Some("unknown") => 0.75,
        Some("documentation") => 0.4,
        Some("test") => 0.3,
        Some("fixture") => 0.2,
        Some("generated") => 0.1,
        Some(_) => 0.0,
    }
}

fn generated_path(components: &[&str], file: &str) -> bool {
    has_component(components, &["generated", "__generated__"])
        || has_file_marker(
            file,
            &[".generated.", ".gen.", "_generated.", "-generated."],
        )
}

fn generated_header(header: &str) -> bool {
    [
        "@generated",
        "auto-generated",
        "autogenerated",
        "automatically generated",
        "this file was generated",
        "generated file - do not edit",
        "generated file. do not edit",
    ]
    .iter()
    .any(|marker| header.contains(marker))
}

fn has_component(components: &[&str], candidates: &[&str]) -> bool {
    components
        .iter()
        .any(|component| candidates.contains(component))
}

fn has_file_marker(file: &str, markers: &[&str]) -> bool {
    markers.iter().any(|marker| file.contains(marker))
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::classify;

    #[test]
    fn classifies_common_repository_roles_with_specific_roles_winning() {
        assert_eq!(
            classify(Path::new("packages/api/src/run.ts"), ""),
            "production"
        );
        assert_eq!(
            classify(Path::new("packages/api/src/run.test.ts"), ""),
            "test"
        );
        assert_eq!(
            classify(Path::new("packages/api/tests/fixtures/run.ts"), ""),
            "fixture"
        );
        assert_eq!(
            classify(Path::new("packages/api/docs/run.stories.tsx"), ""),
            "documentation"
        );
        assert_eq!(
            classify(
                Path::new("packages/api/src/schema.ts"),
                "// @generated\nexport const x = 1;"
            ),
            "generated"
        );
        assert_eq!(
            classify(Path::new("packages/api/tests/generated/run.test.ts"), ""),
            "generated"
        );
    }

    #[test]
    fn singular_doc_directories_are_production_not_documentation() {
        assert_eq!(
            classify(
                Path::new("packages/backend/server/src/core/doc/writer.ts"),
                ""
            ),
            "production"
        );
        assert_eq!(
            classify(
                Path::new("packages/common/nbstore/src/sync/doc/peer.ts"),
                ""
            ),
            "production"
        );
        assert_eq!(
            classify(Path::new("packages/api/docs/guide.ts"), ""),
            "documentation"
        );
        assert_eq!(
            classify(Path::new("packages/api/documentation/guide.ts"), ""),
            "documentation"
        );
        assert_eq!(
            super::penalty(Some(classify(Path::new("src/doc/job.ts"), ""))),
            1.0
        );
    }

    #[test]
    fn classifies_conventional_rust_test_module_filenames() {
        assert_eq!(classify(Path::new("src/parser/test.rs"), ""), "test");
        assert_eq!(classify(Path::new("src/parser/tests.rs"), ""), "test");
        assert_eq!(
            classify(Path::new("src/parser/contest.rs"), ""),
            "production"
        );
        assert_eq!(
            classify(Path::new("src/parser/tests.rs.bak"), ""),
            "production"
        );
    }
}
